### ISSUE TITLE
Issue at link-time when using both gmp and glpk

### ISSUE THREAD

**Issue by pascalito** [nberth/mlgmpidl#1]
I face a problem using mlgmpidl 1.2.4 fetched from opam, compiled with both OCaml compiler chains 4.01.0 and 4.02.3. Here is a simplified version of my problem:
- I have got a program, using simple function of Mpzf. I want to compile this program, and I know that eventually I will need the glpk library from the opam package ocaml-glpk 0.1.6.

`let _ =`
`let m = Mpzf.of_int 42 in`
`Format.printf "%a@\n" Mpzf.print m`
- When I compile my program in **native**, everything is **fine**.

`ocamlbuild -use-ocamlfind -pkgs glpk,gmp main.byte -verbose 1 --`
`42`
- When I compile my program in **bytecode**, everything goes **wrong**.

`ocamlbuild -use-ocamlfind -pkgs glpk,gmp main.byte -verbose 1 --`
`/tmp/cc0hqkIW.o:(.data+0xd40): référence indéfinie vers « camlidl_mpz_mpz__export »`
`[...]`
`/tmp/cc0hqkIW.o:(.data+0xe68): référence indéfinie vers « camlidl_mpz_mpz_init_set »`
`collect2: error: ld returned 1 exit status`
- When I compile my program in **bytecode**, not asking for **glpk**, everything is **fine**.

`ocamlbuild -use-ocamlfind -pkgs gmp main.byte -verbose 1 --`
`42`

After some painful investigation, it seems to me that the error is due to the absence of `-lgmp_caml` in the final gcc invocation when I compile in bytecode. This library (libgmp_caml.a) defines the missing symbols and appears in the final gcc invocation for the native version.

This behaviour only happens with gmp and glpk, or apron and glpk (same missing symbols). Maybe glpk is faulty.

**Important note** : this behaviour does not happen with mlgmpidl 1.2.1, but does happen with mlgmpidl 1.2.2 and 1.2.4.

**Comment by nberth** [comment]
After some investigation, I think this may be due to the way the `glpk` library is built. More precisely, `glpk.cma` is built in custom mode (by passing the `-custom` flag to `ocamlc`), and that does not seem to play well when multiple libraries with shared dependencies to external C libraries are to be linked together.  After rebuilding `ocaml-glpk` with and extra line `NO_CUSTOM = yes` in `src/Makefile` in its source tree, I managed to make your examples compile and execute correctly.

I have no clue yet as to why `glpk.cma` would need to be built in `custom` mode.

**Comment by pascalito** [comment]
The information has been submitted (by mail) to the maintainers of the ocaml-glpk. Hoping some news soon.
