### ISSUE TITLE
Opam install fails with OCaml 4.12 flambda musl static

### ISSUE THREAD

**Issue by jemsab** [nberth/mlgmpidl#11]
Hi,

When trying to install mlgmpidl with `opam install mlgmpidl`, on an opam switch with OCaml 4.12 compiled with flambda, musl and static, I get an error relating to a missing gmp.h file (see error summary below and attached file for details).
The installation seems to also fail on other switches (namely 4.11.1+musl+static+flambda and 4.08.0+musl+static+flambda)
As I understand it all dependencies are installed, please see opam depext command result below.

If there is any advice you could give concerning this error it would be greatly appreciated,

Thanks in advance in any case

**Running `opam depext mlgmpidl` I get :**
\# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
\# The following system packages are needed:
libgmp-dev
libmpfr-dev
perl

\# All required OS packages found.
 
**Error with `opam install mlgmpidl`**
\#=== ERROR while compiling mlgmpidl.1.2.13 ====================================#
\# context     2.0.7 | linux/x86_64 | ocaml-option-flambda.1 ocaml-option-musl.1 ocaml-option-static.1 ocaml-variants.4.12.0+options | https://opam.ocaml.org/#fde0c1b5
\# path        ~/.opam/4.12.0+flambda+static/.opam-switch/build/mlgmpidl.1.2.13
\# command     ~/.opam/opam-init/hooks/sandbox.sh build make
\# exit-code   2
\# env-file    ~/.opam/log/mlgmpidl-30803-6d07ae.env
\# output-file ~/.opam/log/mlgmpidl-30803-6d07ae.out
\### output ###
\# [...]
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c gmp_random.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpzf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpqf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpfrf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlopt -package "bigarray" -ccopt -U__STRICT_ANSI__ -ccopt -UNDEBUG -ccopt -O0 -ccopt -g -ccopt -Wcast-qual -ccopt -Wswitch -ccopt -Wall -ccopt -Wextra -ccopt -Wundef -ccopt -Wcast-align -ccopt -Wno-unused -ccopt -Wno-unused-parameter -ccopt -Wno-unused-function -ccopt -fPIC -ccopt -Werror-implicit-function-declaration -ccopt -Wbad-f[...]
\# In file included from mpz_caml.c:21:0:
\# gmp_caml.h:15:10: fatal error: gmp.h: No such file or directory
\#  #include "gmp.h"
\#           ^~~~~~~
\# compilation terminated.
\# Makefile:273: recipe for target 'mpz_caml.o' failed
\# make: *** [mpz_caml.o] Error 2

[mlgmpidl-30176-6d07ae.txt](https://github.com/nberth/mlgmpidl/files/6848998/mlgmpidl-30176-6d07ae.txt)

**Comment by denismerigoux** [comment]
Hi, this issue is connected to https://github.com/MLanguage/mlang/issues/16 and a compiler for the special language used by the French tax administration to compute the income tax of all French citizens. The OCaml code of the Mlang compiler must compile to a static binary to be used on an old machine. Hope this context can help motivate the resolution of this issue :)

**Comment by nberth** [comment]
Hi,

Thanks for reporting this issue. I've not followed the progress of the OCaml ecosystem towards MUSL much, and inquiring that issue allowed me to catch up a little on that. I think the issue [has already been investigated](https://github.com/ocaml/Zarith/issues/77), and the problem does not seem to lie in the `mlgmpidl` package itself.

Fortunately the issue linked above [gives some clues in the search for a solution](https://github.com/ocaml/Zarith/issues/77#issuecomment-706584811): in order to obtain an executable based on MUSL, statically linked or not, you need to have a MUSL-compatible version of libgmp. The fact that the source code of the execulable is written in OCaml  and involves `mlgmpidl` is incidental.

[There seems to be some fairly old discussion on `gmplib.org` about MUSL](https://gmplib.org/list-archives/gmp-devel/2016-December/004488.html), so in the best case, compiling it can be done with, e.g, `musl-gcc`. Now assuming you can install this MUSL-compatible library and its companion libmpfr within a directory, say `/opt/musl-prefix/`, then appropriately setting `GMP_PREFIX="/opt/musl-prefix"` and `MPFR_PREFIX="/opt/musl-prefix"` environment variables prior to the invocation of `opam install mlgmpidl` should do the trick. Alternatively, manually tuning `CFLAGS` and `LDFLAGS` may work as well. Note I've not had the time to test any of this.

Best,

PS (reminder, to file an issue in `opam-repository` if the above solution works): this error does not pop up via `conf-gmp` and `conf-mpfr` (where I think it should), probably because these packages test using `cc` instead of `ocamlopt`.

**Comment by nberth** [comment]
Hi again,

For the record, the following works for me on `4.08.0+musl+static+flambda`, and seems to produce a valid statically linked program:
```sh
cd /tmp/gmp-prefix

# MUSL-based GMP
wget https://gmplib.org/download/gmp/gmp-6.2.1.tar.lz && tar xaf gmp-6.2.1.tar.lz
( cd gmp-6.2.1; CC=musl-gcc ./configure --prefix /tmp/gmp-prefix && make && make install )

# MUSL-based MPFR
wget https://www.mpfr.org/mpfr-current/mpfr-4.1.0.tar.xz && tar xaf mpfr-4.1.0.tar.xz
( cd mpfr-4.1.0; CC=musl-gcc ./configure --prefix /tmp/gmp-prefix -with-gmp=/tmp/gmp-prefix && make && make install )

# Install mlgmpidl with custom prefixes
MPFR_PREFIX=/tmp/gmp-prefix GMP_PREFIX=/tmp/gmp-prefix opam install mlgmpidl

# Compile and link a small program
ocamlfind ocamlopt -o test -ccopt -static -package gmp -linkpkg test.ml -verbose
./test
# should successfully terminate and print "1764"

# Check we indeed have a statically linked program
musl-ldd test
# should print "musl-ldd: test: Not a valid dynamic program"
````
    
with `/tmp/gmp-prefix/test.ml`:
````ocaml
(* Quick test of proper linking *)
module Z = Mpzf
let x = Z.of_int 42;;
Format.printf "%a@." Z.print (Z.mul x x);;
````

`mlgmpidl` currently requires that dynamic libraries for GMP and MPFR be present; if dynamically loaded libraries are to be avoided at all cost, a workaround is possible via a manual compilation of the source code.

Best,

**Comment by denismerigoux** [comment]
Hi @nberth, thanks very much for your thorough explanation and for providing us a useful guide for getting and compiling the GMP and MPFR libraries. We've been working on this yesterday and today, and ended up installing GMP and MPFR on the old machine isolated from the main Internet by some complex workarounds. In the end, we've been able to compile our Mlang compiler properly using dynamic linking.

However, your instructions for static linking will be valuable for the project, since I may intend to distribute a standalone binary of the compiler at some point. We'll keep them in mind, but I think you can close the issue at this point.

**Comment by jemsab** [comment]
Hi @nberth, I'd just like to join Denis in thanking you for all the effort you put in to answering our issue and going above and beyond with your detailed instructions!
